#server:
#  port: 8086
#spring:
#  application:
#    name: trade-service
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3307/hm-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#  cloud:
#    nacos:
#      server-addr: 192.168.121.162:8848
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.trade: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#knife4j:
#  enable: true
#  openapi:
#    title: 交易接口文档
#    description: "交易接口文档"
#    email: zhanghuyi@itcast.cn
#    concat: 虎哥
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.trade.controller
#feign:
#  okhttp:
#    enabled: true
## keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123


server:
  port: 8086
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 交易服务接口文档
    package: com.trade.controller
  db:
    database: hm-trade
spring:
  rabbitmq:
    host: 192.168.121.162 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: itheima # 用户名
    password: 123321 # 密码
